"""Emit LaTeX tables + text snippets for the manuscript, generated from the
measured result files so the paper's numbers cannot drift from the data.

  python scripts/09_latex_tables.py

Outputs under results/evaluation/latex/:
  table_timing.tex        simulator vs surrogate wall time (speed-up)
  table_offgrid.tex       off-grid validation against the physical model
  snippet_offgrid.tex     suggested paragraph, numbers filled in
  snippet_speedup.tex     suggested paragraph, numbers filled in
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from s175.columns import OUTPUT_COLS, UNITS

EV = ROOT / "results" / "evaluation"
DEST = EV / "latex"

NICE = {"speed": "Ship speed", "power": "Brake power", "torque": "Brake torque",
        "lat_acc": "Lateral acc.\\ RMS", "MSI": "MSI", "roll": "Roll RMS",
        "slam": "Slamming prob.", "green_water": "Green water prob.",
        "prop_emerg": "Prop.\\ emergence prob.", "fuel": "Fuel consumption"}


def read_csv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def write(name, text):
    DEST.mkdir(parents=True, exist_ok=True)
    (DEST / name).write_text(text)
    print("wrote", DEST / name)


def fmt_seconds(s):
    s = float(s)
    if s >= 1:
        return f"{s:.2f}\\,s"
    if s >= 1e-3:
        return f"{s * 1e3:.2f}\\,ms"
    return f"{s * 1e6:.2f}\\,\\textmu s"


def table_timing():
    rows = read_csv(EV / "timing_table.csv")
    lines = [
        "% generated by scripts/09_latex_tables.py -- do not edit numbers by hand",
        "\\begin{table}[ht]\\centering",
        "\\caption{Measured wall time per evaluated operating point. The",
        "surrogate figures include all three networks (regressor and both",
        "feasibility classifiers) on a single GPU; the simulator baseline is",
        "the WeatherRouting binary on the same host.}",
        "\\label{tab:timing}",
        "\\begin{tabular}{lrr}\\hline",
        "Configuration & Time per point & Speed-up \\\\ \\hline",
    ]
    for r in rows:
        sp = float(r["speedup_vs_simulator_single"])
        sp_s = "--" if sp == 1.0 else f"$\\times{sp:,.0f}$"
        lines.append(f"{r['configuration']} & {fmt_seconds(r['seconds_per_point'])} & {sp_s} \\\\")
    lines += ["\\hline\\end{tabular}\\end{table}", ""]
    write("table_timing.tex", "\n".join(lines))
    return rows


def table_offgrid():
    data = json.loads((EV / "interpolation_test.json").read_text())
    lines = [
        "% generated by scripts/09_latex_tables.py -- do not edit numbers by hand",
        "\\begin{table}[ht]\\centering",
        "\\caption{Validation against fresh simulator runs at inputs strictly",
        "between the training grid levels (off-grid). Midpoint design:",
        f"{data['midpoint']['n_rows']:,} points; random design:",
        f"{data['random']['n_rows']:,} points. Over-prediction rates are",
        "computed on positive-truth rows; the safe side is over-prediction for",
        "every output except ship speed.}",
        "\\label{tab:offgrid}",
        "\\begin{tabular}{lrrrr}\\hline",
        " & \\multicolumn{2}{c}{$R^2$} & \\multicolumn{2}{c}{Over-prediction [\\%]} \\\\",
        "Output & midpoint & random & midpoint & random \\\\ \\hline",
    ]
    for c in OUTPUT_COLS:
        a = data["midpoint"]["regressor"]["per_output"][c]
        b = data["random"]["regressor"]["per_output"][c]
        lines.append(
            f"{NICE[c]} & {a['R2']:.4f} & {b['R2']:.4f} & "
            f"{a['overpred_pct_positive']:.1f} & {b['overpred_pct_positive']:.1f} \\\\")
    lines += ["\\hline\\end{tabular}\\end{table}", ""]
    write("table_offgrid.tex", "\n".join(lines))
    return data


def table_seed_spread():
    data = json.loads((EV / "s1_seed_spread.json").read_text())
    lines = [
        "% generated by scripts/09_latex_tables.py -- do not edit numbers by hand",
        "\\begin{table}[ht]\\centering",
        "\\caption{Seed variability on the random split: the regressor was",
        "trained with three random seeds under identical configuration and",
        "evaluated on the same test subset. $R^2$ is reported as the",
        "three-seed mean with the standard deviation and the worst seed; MAE",
        "as mean $\\pm$ standard deviation in the output's units.}",
        "\\label{tab:seeds}",
        "\\begin{tabular}{lccc}\\hline",
        "Output & $R^2$ mean $\\pm$ SD & min $R^2$ & MAE mean $\\pm$ SD \\\\ \\hline",
    ]
    def sci(x):
        m, e = f"{x:.1e}".split("e")
        return f"{m} \\times 10^{{{int(e)}}}"

    for c in OUTPUT_COLS:
        r2 = data["R2"][c]
        mae = data["MAE"][c]
        lines.append(
            f"{NICE[c]} & ${r2['mean']:.5f} \\pm {sci(r2['std'])}$ & "
            f"{r2['min']:.5f} & ${mae['mean']:.4g} \\pm {mae['std']:.1g}$ \\\\")
    lines += ["\\hline\\end{tabular}\\end{table}", ""]
    write("table_seed_spread.tex", "\n".join(lines))


def snippets(timing_rows, offgrid):
    sim_single = float(timing_rows[0]["seconds_per_point"])
    sur_batch = float(timing_rows[3]["seconds_per_point"])
    sur_single = float(timing_rows[2]["seconds_per_point"])
    speedup_batch = sim_single / sur_batch
    write("snippet_speedup.tex", f"""% suggested text -- edit style freely, numbers are measured
The surrogate replaces a simulator call of {sim_single:.2f}\\,s (median,
single operating point) with a forward pass of
{sur_single * 1e3:.1f}\\,ms for a single point and
{sur_batch * 1e6:.2f}\\,\\textmu s per point when batched on one GPU ---
a measured speed-up of $\\approx {speedup_batch / 10 ** (len(str(int(speedup_batch))) - 1):.1f}
\\times 10^{{{len(str(int(speedup_batch))) - 1}}}$, which turns exhaustive sweeps of the
operating envelope from a cluster-scale computation into an interactive one.
""")
    mid = offgrid["midpoint"]
    rnd = offgrid["random"]
    mid_meta = mid["regressor"]["meta"]
    rnd_meta = rnd["regressor"]["meta"]
    r2_min_mid = min(v["R2"] for v in mid["regressor"]["per_output"].values())
    r2_min_rnd = min(v["R2"] for v in rnd["regressor"]["per_output"].values())
    write("snippet_offgrid.tex", f"""% suggested text -- edit style freely, numbers are measured
To test the surrogate at inputs it has never seen, the physical model was
re-run at operating points lying strictly between the training grid levels:
a midpoint design ({mid['n_rows']:,} points) and a random-position design
({rnd['n_rows']:,} points). Accuracy is preserved in both
($R^2 \\geq {r2_min_mid:.3f}$ and $R^2 \\geq {r2_min_rnd:.3f}$ over all ten
outputs). The engineered error direction also largely transfers: all ten
outputs err on their safe side at the midpoints
({mid_meta['safe_direction_met']}/{mid_meta['safe_direction_total']}), and
{rnd_meta['safe_direction_met']} of ten at random positions --- the
directional bias, unlike the accuracy, is therefore not guaranteed away from
the training grid, and the feasibility classifier's recall declines from
{mid['clf1']['recall']:.3f} to {rnd['clf1']['recall']:.3f} there
(Table~\\ref{{tab:offgrid}}).
""")


def main() -> int:
    timing_rows = table_timing()
    offgrid = table_offgrid()
    table_seed_spread()
    snippets(timing_rows, offgrid)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
