"""Loss-configuration ablation: table + figure from the four same-protocol runs.

All four arms are trained by scripts/02_train.py on the S1_random split, seed 0,
identical optimisation schedule, and scored on identical test rows:

  v1_original           the original v1 configuration: uniform alpha=1.5, no
                        fuel mask (fuel-only rows dropped), BN after activation
  abl_uniform_masked    uniform alpha=1.5, fuel mask     (v3 data handling)
  abl_symmetric_masked  symmetric alpha=1.0, fuel mask   (v3 data handling)
  v3_masked_peroutput   per-output alpha (1.5/0.33), fuel mask

The three masked arms differ only in the weighting.

This replaces the earlier comparison against the original v1 checkpoint,
whose training split overlapped these test rows.

Run after scripts/03_evaluate.py has produced eval.json for every arm:
  python scripts/12_loss_ablation.py

Outputs:
  results/evaluation/ablation_loss_comparison.csv
  results/evaluation/latex/table_loss_ablation.tex
  figures/fig_loss_ablation_safety.{png,pdf}
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from s175.columns import OUTPUT_COLS, SAFE_DIRECTION
from s175.labels import output_label

EV = ROOT / "results" / "evaluation"

# plot order: the progression toward the selected configuration, light -> dark
# reader-facing labels: no internal version codenames (v1/v3) in paper assets
ARMS = [
    ("v1_original",          "original configuration", "#c4d7ea", "o"),
    ("abl_unmasked_fixedbn", "uniform α=1.5, unmasked",        "#a9c6e2", "v"),
    ("abl_uniform_masked",   "uniform α=1.5, masked",          "#6f9fd0", "s"),
    ("abl_symmetric_masked", "symmetric α=1.0, masked",        "#31538f", "^"),
    ("v3_masked_peroutput",  "per-output α, masked (selected)", "#14284a", "D"),
]
NICE = {"speed": "Ship speed", "power": "Brake power", "torque": "Brake torque",
        "lat_acc": "Lateral acc.\\ RMS", "MSI": "MSI", "roll": "Roll RMS",
        "slam": "Slamming prob.", "green_water": "Green water prob.",
        "prop_emerg": "Prop.\\ emergence prob.", "fuel": "Fuel consumption"}


def load(name, eval_name="eval.json"):
    p = ROOT / "runs" / name / "S1_random" / "seed_0" / eval_name
    if not p.exists() and eval_name != "eval.json":
        raise SystemExit(f"{p} missing -- run 03_evaluate.py --clean "
                         f"--config-name {name} first")
    return json.loads(p.read_text())["regressor"]


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--clean", action="store_true",
                    help="use eval_clean.json (screening-disjoint test rows)")
    args = ap.parse_args()
    eval_name = "eval_clean.json" if args.clean else "eval.json"
    regs = {name: load(name, eval_name) for name, *_ in ARMS}

    # ------------------------------------------------------------- CSV
    with open(EV / "ablation_loss_comparison.csv", "w", newline="") as f:
        w = csv.writer(f)
        head = ["output", "safe_direction"]
        for name, *_ in ARMS:
            head += [f"{name}_R2", f"{name}_overpred_pct", f"{name}_safe_met"]
        w.writerow(head)
        for c in OUTPUT_COLS:
            row = [c, SAFE_DIRECTION[c]]
            for name, *_ in ARMS:
                po = regs[name]["per_output"][c]
                row += [po["R2"], po["overpred_pct_positive"],
                        po["safe_direction_met"]]
            w.writerow(row)
    print("wrote", EV / "ablation_loss_comparison.csv")

    # ------------------------------------------------------------- LaTeX
    heads = " & ".join(lbl for _, lbl, *_ in ARMS)
    lines = [
        "% generated by scripts/12_loss_ablation.py -- do not edit numbers by hand",
        "\\begin{table*}[ht]\\centering",
        "\\caption{Loss-configuration ablation: five arms trained under the",
        "same protocol on the random split and scored on identical",
        "screening-disjoint test rows. Cells give the over-prediction rate on",
        "positive-truth rows; a \\checkmark{} marks an output whose errors lie",
        "preferentially on its safe side.}",
        "\\label{tab:lossablation}",
        "\\begin{tabular}{llrrrrr}\\hline",
        "Output & Safe side & " + heads.replace("α", "$\\alpha$") + " \\\\ \\hline",
    ]
    for c in OUTPUT_COLS:
        cells = []
        for name, *_ in ARMS:
            po = regs[name]["per_output"][c]
            mark = "\\,\\checkmark" if po["safe_direction_met"] else ""
            cells.append(f"{po['overpred_pct_positive']:.1f}{mark}")
        lines.append(f"{NICE[c]} & {SAFE_DIRECTION[c]} & " + " & ".join(cells) + " \\\\")
    lines.append("\\hline")
    totals = " & ".join(
        f"{regs[name]['meta']['safe_direction_met']}/{regs[name]['meta']['safe_direction_total']}"
        for name, *_ in ARMS)
    lines.append(f"Outputs on safe side & & {totals} \\\\ \\hline")
    lines += ["\\end{tabular}\\end{table*}", ""]
    (EV / "latex").mkdir(parents=True, exist_ok=True)
    (EV / "latex" / "table_loss_ablation.tex").write_text("\n".join(lines))
    print("wrote", EV / "latex" / "table_loss_ablation.tex")

    # ------------------------------------------------------------- figure
    fig, ax = plt.subplots(figsize=(7.0, 3.3))
    ys = np.arange(len(OUTPUT_COLS))[::-1]
    ax.axvline(50, color="k", lw=0.8, ls=":", zorder=1)
    for i, y in enumerate(ys):
        want_over = SAFE_DIRECTION[OUTPUT_COLS[i]] == "over"
        # shade each output's safe half of the axis
        ax.barh(y, 50, left=50 if want_over else 0,
                height=0.9, color="#eef3f9", zorder=0)
    for name, lbl, color, marker in ARMS:
        rates = [regs[name]["per_output"][c]["overpred_pct_positive"]
                 for c in OUTPUT_COLS]
        ax.scatter(rates, ys, s=24, color=color, marker=marker, label=lbl,
                   zorder=3, edgecolors="white", linewidths=0.6)
    for i, y in enumerate(ys):
        want_over = SAFE_DIRECTION[OUTPUT_COLS[i]] == "over"
        ax.annotate("safe →" if want_over else "← safe",
                    (98 if want_over else 2, y),
                    ha="right" if want_over else "left", va="center",
                    fontsize=7.5, color="#5a6b7f", zorder=2)
    ax.set_yticks(ys, [output_label(c) for c in OUTPUT_COLS], fontsize=8)
    ax.set_xlim(0, 100)
    ax.tick_params(axis="x", labelsize=8)
    ax.set_xlabel("over-prediction rate on positive-truth rows [%]", fontsize=8)
    ax.legend(fontsize=7.5, loc="upper center", bbox_to_anchor=(0.45, -0.17),
              ncol=3, frameon=False, handletextpad=0.3, columnspacing=1.2)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(ROOT / "figures" / "fig_loss_ablation_safety.png", dpi=300,
                bbox_inches="tight")
    fig.savefig(ROOT / "figures" / "fig_loss_ablation_safety.pdf",
                bbox_inches="tight")
    print("wrote figures/fig_loss_ablation_safety.{png,pdf}")

    for name, lbl, *_ in ARMS:
        m = regs[name]["meta"]
        print(f"  {name:22s} {lbl:32s} safe-direction "
              f"{m['safe_direction_met']}/{m['safe_direction_total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
