"""Emit the manuscript's results tables from the screening-disjoint evals.

Reads runs/v3_masked_peroutput/*/seed_*/eval_clean.json (03_evaluate.py
--clean) and writes, under results/evaluation/latex/:

  table_classifiers_clean.tex   tab:classifiers  (S1 seed 0, clean rows)
  table_regression_clean.tex    tab:regression   (S1 seed 0, clean rows)
  table_seeds_clean.tex         tab:seeds        (S1 seeds 0-2, clean rows)
  table_general_clean.tex       tab:general      (all regimes, clean rows)
  paper_numbers_clean.json      every in-text number the results section cites

  python scripts/18_paper_tables_clean.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from s175.columns import OUTPUT_COLS

RUNS = ROOT / "runs" / "v3_masked_peroutput"
DEST = ROOT / "results" / "evaluation" / "latex"

NICE = {"speed": "Ship speed [kn]", "power": "Brake power [kW]",
        "torque": "Brake torque [kNm]", "lat_acc": "Lateral acc.\\ RMS [g]",
        "MSI": "Motion sickness [\\%]", "roll": "Rolling RMS [deg]",
        "slam": "Slamming prob.\\ [\\%]",
        "green_water": "Green water prob.\\ [\\%]",
        "prop_emerg": "Prop.\\ emergence [\\%]",
        "fuel": "Fuel consumption [kg/nm]"}
NICE_SHORT = {"speed": "Ship speed", "power": "Brake power",
              "torque": "Brake torque", "lat_acc": "Lateral acc.\\ RMS",
              "MSI": "MSI", "roll": "Roll RMS", "slam": "Slamming prob.",
              "green_water": "Green water prob.",
              "prop_emerg": "Prop.\\ emergence prob.", "fuel": "Fuel consumption"}
REGIME = {"S1_random": "Random split", "S2_level_Hs": "Unseen $H_s$ levels",
          "S2_level_Chi": "Unseen $\\chi$ levels",
          "S2_level_draft": "Unseen draft level",
          "S2_level_Vwind": "Unseen $V_\\mathrm{wind}$ levels",
          "S3_block": "Block holdout", "S4_corner": "Corner extrapolation"}
ORDER = list(REGIME)


def load(split, seed):
    p = RUNS / split / f"seed_{seed}" / "eval_clean.json"
    return json.loads(p.read_text())


def sig4(x):
    """Format to ~4 significant digits like the manuscript's tables."""
    if x == 0:
        return "0"
    exp = int(np.floor(np.log10(abs(x))))
    dec = max(0, 3 - exp)
    return f"{x:.{dec}f}"


def group(n):
    return f"{n:,}".replace(",", "{,}")


def main() -> int:
    DEST.mkdir(parents=True, exist_ok=True)
    e0 = load("S1_random", 0)

    # ------------------------------------------------ tab:classifiers
    lines = ["% generated by scripts/18_paper_tables_clean.py -- clean primary"]
    for name, label in (("clf1", "C1 (complete infeasibility)"),
                        ("clf2", "C2 (fuel-only infeasibility)")):
        m = e0[name]
        lo, hi = (100 * v for v in m["false_negative_rate_ci95"])
        lines.append(
            f"{label} & {e0['thresholds'][name]:.2f} & {m['recall']:.4f} & "
            f"{m['precision']:.5f} & {m['accuracy']:.4f} & {group(m['FN'])} & "
            f"{100 * m['false_negative_rate']:.2f} $[{lo:.2f}, {hi:.2f}]$ \\\\")
    (DEST / "table_classifiers_clean.tex").write_text("\n".join(lines) + "\n")

    # ------------------------------------------------ tab:regression
    lines = ["% generated by scripts/18_paper_tables_clean.py -- clean primary"]
    for c in OUTPUT_COLS:
        m = e0["regressor"]["per_output"][c]
        lines.append(
            f"{NICE[c]} & {sig4(m['MAE'])} & {sig4(m['RMSE'])} & "
            f"{m['R2']:.5f} & {m['rel_MAE_sd_pct']:.2f} & "
            f"{m['overpred_pct_positive']:.1f} \\\\")
    (DEST / "table_regression_clean.tex").write_text("\n".join(lines) + "\n")

    # ------------------------------------------------ tab:seeds
    seeds = [load("S1_random", s) for s in (0, 1, 2)]
    lines = ["% generated by scripts/18_paper_tables_clean.py -- clean primary"]
    for c in OUTPUT_COLS:
        r2 = np.array([e["regressor"]["per_output"][c]["R2"] for e in seeds])
        mae = np.array([e["regressor"]["per_output"][c]["MAE"] for e in seeds])
        sd = r2.std(ddof=1)
        exp = int(np.floor(np.log10(sd))) if sd > 0 else 0
        sd_tex = f"{sd / 10**exp:.1f} \\times 10^{{{exp}}}"
        mae_sd = mae.std(ddof=1)
        mexp = int(np.floor(np.log10(mae_sd))) if mae_sd > 0 else 0
        mae_sd_tex = (f"{mae_sd:.{max(0, 1 - mexp)}f}" if mexp >= -3
                      else f"{mae_sd / 10**mexp:.0f} \\times 10^{{{mexp}}}")
        lines.append(
            f"{NICE_SHORT[c]} & ${r2.mean():.5f} \\pm {sd_tex}$ & "
            f"{r2.min():.5f} & ${sig4(mae.mean())} \\pm {mae_sd_tex}$ \\\\")
    (DEST / "table_seeds_clean.tex").write_text("\n".join(lines) + "\n")

    # ------------------------------------------------ tab:general
    lines = ["% generated by scripts/18_paper_tables_clean.py -- clean primary"]
    for split in ORDER:
        e = load(split, 0)
        z = e["end_to_end"]
        min_r2 = min(e["regressor"]["per_output"][c]["R2"] for c in OUTPUT_COLS)
        lines.append(
            f"{REGIME[split]} & {group(e['n_test_rows'])} & "
            f"{z['accuracy']:.4f} & {min_r2:.4f} & "
            f"{100 * z['dangerous_allneg_rate']:.2f} & "
            f"{100 * z['dangerous_fuel_rate']:.2f} \\\\")
    (DEST / "table_general_clean.tex").write_text("\n".join(lines) + "\n")

    # ------------------------------------------------ in-text numbers
    z = e0["end_to_end"]
    counts = e0["test_class_counts"]
    nums = {
        "n_clean_test_rows": e0["n_test_rows"],
        "n_screening_rows_excluded": e0["n_screening_rows_excluded"],
        "test_class_counts": counts,
        "three_class_accuracy": z["accuracy"],
        "balanced_accuracy": z["balanced_accuracy"],
        "macro_f1": z["macro_f1"],
        "per_class_recall": z["per_class_recall"],
        "clf1": {k: e0["clf1"][k] for k in
                 ("recall", "precision", "FN", "FP", "false_negative_rate",
                  "false_negative_rate_ci95", "n_negative")},
        "clf2": {k: e0["clf2"][k] for k in
                 ("recall", "precision", "FN", "FP", "false_negative_rate",
                  "false_negative_rate_ci95")},
        "min_R2_by_split": {s: min(load(s, 0)["regressor"]["per_output"][c]["R2"]
                                   for c in OUTPUT_COLS) for s in ORDER},
        "max_rel_MAE_sd_pct": max(e0["regressor"]["per_output"][c]["rel_MAE_sd_pct"]
                                  for c in OUTPUT_COLS),
        "min_R2": min(e0["regressor"]["per_output"][c]["R2"] for c in OUTPUT_COLS),
        "overpred_speed": e0["regressor"]["per_output"]["speed"]["overpred_pct_positive"],
        "overpred_others_range": [
            min(e0["regressor"]["per_output"][c]["overpred_pct_positive"]
                for c in OUTPUT_COLS if c != "speed"),
            max(e0["regressor"]["per_output"][c]["overpred_pct_positive"]
                for c in OUTPUT_COLS if c != "speed")],
        "seed_spread_max_R2_sd": max(
            float(np.std([load("S1_random", s)["regressor"]["per_output"][c]["R2"]
                          for s in (0, 1, 2)], ddof=1)) for c in OUTPUT_COLS),
        "seed_spread_min_R2": min(
            load("S1_random", s)["regressor"]["per_output"][c]["R2"]
            for s in (0, 1, 2) for c in OUTPUT_COLS),
    }
    (DEST / "paper_numbers_clean.json").write_text(json.dumps(nums, indent=2))
    for f in ("table_classifiers_clean.tex", "table_regression_clean.tex",
              "table_seeds_clean.tex", "table_general_clean.tex",
              "paper_numbers_clean.json"):
        print("wrote", DEST / f)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
