"""Joint loss-weight grid on the screening split.

The two weights interact: the ten outputs share the MLP hidden layers, so
changing the nine non-speed weights also moves the speed predictions. A
sequential search (pick alpha_speed under uniform weighting, then vary the
rest) cannot see that interaction, so every (alpha_speed, alpha_other) pair is
trained jointly:

    alpha_speed in {1.0, 1.5, 2.0, 3.0, 5.0}
    alpha_other in {1.5, 1.0, 0.8, 0.67, 0.5, 0.33}

30 configurations x SEEDS seeds, regressor only, on S0_screen, through the
standard 02_train.py path so every run carries the usual provenance record.
Each pair is trained exactly once per seed -- the uniform (1.5, 1.5) point is
one configuration, not two.

The grid deliberately contains pairs on both sides of every output's safe
direction; the configs state `ablation_loss: true` so the SAFE_DIRECTION
guard, whose job is to stop *accidental* violations, does not veto the search
space. The direction requirement is enforced instead by the selection rule
(22_alpha_grid_select.py), where it belongs.

A run whose run.json already exists is skipped, so the driver is resumable.
A failed run is reported and does not stop the grid.

  python scripts/20_alpha_grid.py [--seeds 0 1 2 3 4] [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ALPHA_SPEED = [1.0, 1.5, 2.0, 3.0, 5.0]
ALPHA_OTHER = [1.5, 1.0, 0.8, 0.67, 0.5, 0.33]
SEEDS = [0, 1, 2, 3, 4]
SPLIT = "S0_screen"
CONFIG_DIR = ROOT / "configs" / "grid"

CONFIG_TEMPLATE = """\
# Generated by 20_alpha_grid.py -- one point of the joint loss-weight grid.
# Identical to v3_masked_peroutput except for the two alpha values; the batch
# size and AMP come from the timing pilot at run time, as in every run.
name: {name}
description: >
  Loss-weight grid point alpha_speed={a_speed}, alpha_other={a_other},
  regressor only, on the screening split.

split: {split}
ablation_loss: true    # the grid spans both sides of SAFE_DIRECTION on purpose

hidden: [512, 256, 128]
batchnorm: true
bn_after_act: false
dropout: 0.0

alpha_speed: {a_speed}
alpha_others: {a_other}

lr: 0.001
batch_size: 512        # fallback only; the timing pilot's optimum wins
max_epochs: 200
patience: 15
amp: true
"""


def log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def config_name(a_speed: float, a_other: float) -> str:
    return f"grid_a{a_speed:g}_o{a_other:g}"


def write_configs() -> list[Path]:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    paths = []
    for a_speed in ALPHA_SPEED:
        for a_other in ALPHA_OTHER:
            name = config_name(a_speed, a_other)
            p = CONFIG_DIR / f"{name}.yaml"
            text = CONFIG_TEMPLATE.format(name=name, a_speed=a_speed,
                                          a_other=a_other, split=SPLIT)
            if not p.exists() or p.read_text() != text:
                p.write_text(text)
            paths.append(p)
    return paths


def run_done(name: str, seed: int) -> bool:
    p = ROOT / "runs" / name / SPLIT / f"seed_{seed}" / "run.json"
    if not p.exists():
        return False
    run = json.loads(p.read_text())
    # A subsampled record is a smoke run, never a grid result.
    return run.get("subsample") in (None, 0) and "regressor" in run.get("components", {})


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, nargs="+", default=SEEDS)
    ap.add_argument("--dry-run", action="store_true",
                    help="list what would run, launch nothing")
    args = ap.parse_args()

    configs = write_configs()
    log(f"{len(configs)} grid configs in {CONFIG_DIR}")

    todo = []
    for p in configs:
        name = p.stem
        for seed in args.seeds:
            if run_done(name, seed):
                continue
            todo.append((p, name, seed))
    done = len(configs) * len(args.seeds) - len(todo)
    log(f"{done} runs already complete, {len(todo)} to go")
    if args.dry_run:
        for p, name, seed in todo:
            log(f"  would run {name} seed {seed}")
        return 0

    failures = []
    for i, (p, name, seed) in enumerate(todo, 1):
        log(f"[{i}/{len(todo)}] {name} seed {seed}")
        t0 = time.perf_counter()
        # One process per run: the RNG state, CUDA context and allocator all
        # start fresh, so a run's trajectory cannot depend on what ran before
        # it in the grid.
        r = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "02_train.py"),
             "--config", str(p), "--split", SPLIT,
             "--component", "regressor", "--seed", str(seed)],
            cwd=ROOT,
        )
        dt = time.perf_counter() - t0
        if r.returncode != 0:
            failures.append((name, seed, r.returncode))
            log(f"  FAILED (exit {r.returncode}) after {dt/60:.1f} min")
        else:
            log(f"  done in {dt/60:.1f} min")

    if failures:
        log(f"{len(failures)} runs failed:")
        for name, seed, code in failures:
            log(f"  {name} seed {seed} (exit {code})")
        return 1
    log("grid complete")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
